### PR TITLE
Email Verification done

### PR DESCRIPTION
**Pull request by ShisuiUzumaki**
Email provided by user is verified

### CODE REVIEW

**Comment by bilalshahzad139** [comment]
1) Please convert all queries into Stored Procedure format.  2) WebPrac.csproj.user file should be part of git ignore.

**Comment by ShisuiUzumaki** [comment]
> 1. Please convert all queries into Stored Procedure format.  2) WebPrac.csproj.user file should be part of git ignore.

**Comment by ShisuiUzumaki** [comment]
> 1. Please convert all queries into Stored Procedure format.  2) WebPrac.csproj.user file should be part of git ignore.

But sir there are a lot of queries performing the same task but with different parameters

**Comment by ShisuiUzumaki** [comment]
Sir I am too busy with my other subjects and their assignments and projects. and because of so much work i have to use laptop all day and as you may know my eyesight problem  So, I request you too assign the query to stored procedure  conversion task to someone else @bilalshahzad139

**Pull request closed without merging**
