### PR TITLE
Feature/issue 9

### PR DESCRIPTION
**Pull request by Ali-Bhatti**
Login and Signup pages with client side and server side validation are done

### CODE REVIEW

**Comment by bilalshahzad139** [comment]
Please resolve conflicts. You can resolve these online.

**Comment by Ali-Bhatti** [comment]
> Please resolve conflicts. You can resolve these online.

**Comment by Ali-Bhatti** [comment]
> Please resolve conflicts. You can resolve these online.

Sir can you tell me how to resolve it online?

**Comment by bilalshahzad139** [comment]
Sure, Let's connect on zoom at 5:30. I've shared link in group.

**Comment by Ali-Bhatti** [comment]
> Sure, Let's connect on zoom at 5:30. I've shared link in group.

Okay , Sir.

**Pull request merged**
